### ISSUE TITLE
PHP Notice in example: 'Custom typography options'

### ISSUE THREAD

**Issue by pintomena** [devinsays/options-framework-theme#165]
Using type typography whit options (example: 'Custom typography options' ) in log file I get:

PHP Notice:  Array to string conversion in /Users/pinto/Sites/themebit/wp-includes/general-template.php on line 2408

thanks

**Comment by weblegko** [comment]
still error with customtypography field  wordpress 4.5.3 
Notice: Array to string conversion in D:\www\doctor\wp-includes\general-template.php on line 3550
