### ISSUE TITLE
Strict standards error class-options-interface.php on line 47

### ISSUE THREAD

**Issue by grappler** [devinsays/options-framework-theme#190]
Hey, I am [reviewing a theme](https://themes.trac.wordpress.org/ticket/21833) where I can getting a strict standards warning on the settings page.
```
Strict standards: Non-static method Options_Framework::get_option_name() should not be called statically in /wp-content/themes/accesspress-staple/inc/options-framework/includes/class-options-interface.php on line 47
```

I was able to resolve it by changing [line 25 in class-options-framework.php](https://github.com/devinsays/options-framework-theme/blob/master/inc/includes/class-options-framework.php#L25) to `static function get_option_name() {`

**Comment by devinsays** [comment]
Which version of PHP are you testing with? I'll see if I can recreate.

**Comment by grappler** [comment]
I was testing the theme on VVV so that server info is:
```
PHP Version:              5.5.9-1ubuntu4.5
MySQL Version:            5.5.40
Webserver Info:           nginx/1.7.8
```

**Comment by devinsays** [comment]
I responded in ticket. I think there must be something else going on with their code. No strict warnings when I test this latest version, even using the old method of setting the option name.
