### ISSUE TITLE
Add Theme Options as a menu page rather than item of Appearance?

### ISSUE THREAD

**Issue by mrwigster** [devinsays/options-framework-theme#191]
Is there any option to add this as a direct menu item underneath 'Plugins' for example in the Wordpress admin sidebar, as opposed to a sub menu of 'Appearance'.

I have tried using the 'add_menu_page' WP func in the 'class-options-framework-admin.php' file, however it's quite confusingly nested.

**Comment by devinsays** [comment]
Yes, you can do that.

Use this filter:

```
return apply_filters( 'optionsframework_menu', $menu );
```

See: https://github.com/devinsays/options-framework-theme/blob/master/inc/includes/class-options-framework-admin.php#L83
