### ISSUE TITLE
The output of the options should be escaped in the example

### ISSUE THREAD

**Issue by grappler** [devinsays/options-framework-theme#192]
It would be good a good example to escape the options on out in the examples. https://github.com/devinsays/options-framework-theme/blob/master/index.php

e.g. from

``` php
<?php echo of_get_option( 'example_textarea', 'no entry' ); ?>
```

to

``` php
<?php echo esc_textarea( of_get_option( 'example_textarea', 'no entry' ) ); ?>
```

**Comment by devinsays** [comment]
Yeah, that is a good idea. I'll update the examples.
