### ISSUE TITLE
Add new slides

### ISSUE THREAD

**Issue by rajatchodhary** [devinsays/options-framework-theme#194]
I want to build a slider in which number of slides is not pre-defined. User can add a slide with help of a button to add new slide. How can I do that? A little code help will be appreciated.

**Comment by devinsays** [comment]
There isn't a way to create new options on the fly. You can create a number of pre-defined items (use a loop if you like), then use CSS/JS to hide/show the unfilled ones.

However, slides feel like content (not options). So I generally recommend using a custom post type or actual posts to do that.
