### ISSUE TITLE
Optionsframework sidebar appear outside optionsframework-metabox div

### ISSUE THREAD

**Issue by chodhary** [devinsays/options-framework-theme#201]
Hello Devin,

I want to add sidebar into my theme option page. I took approach as describe in your blog post, and it worked well. It is supposed to appear right next to the options pane. Instead, sidebar is appearing on the bottom right side of options page. When I inspected element, I found that that sidebar panel is out of optionsframework-metabox division, not usual main+sidebar.

Please, enlighten us on this issue.

http://wptheming.com/2012/07/options-framework-sidebar/

**Comment by devinsays** [comment]
I've just made the demos public. You can look at the styles for the sidebar option: https://github.com/devinsays/options-framework-theme-demos/tree/master/options-sidebar
