### ISSUE TITLE
Version 1.9.1 issue

### ISSUE THREAD

**Issue by HooThemes** [devinsays/options-framework-theme#202]
Theme Check Version 20150818.1 test : pass
Upload to WordPress.org: Fail

Results of Automated Theme Scanning: Fail

REQUIRED: class-options-framework-admin.php. Themes should use add_theme_page() for adding admin pages.
Line 34: add_action( 'admin_menu', array( $this, 'add_custom_options_page' ) );
Line 110: function add_custom_options_page() {

**Comment by shizhua** [comment]
Let's ignore the fail messages.
WordPress.org Now Requires Theme Authors to Use the Customizer to Build Theme Options
http://wptavern.com/wordpress-org-now-requires-theme-authors-to-use-the-customizer-to-build-theme-options

**Comment by devinsays** [comment]
The comment by shizhua's is correct. If you'd like to continue using the Options Framework, you'll have to support the plugin version.
