### ISSUE TITLE
PHP 7.1 error with Multicheck type

### ISSUE THREAD

**Issue by bnecreative** [devinsays/options-framework-theme#208]
When using the multicheck field and PHP 7.1, an error occurs when no items are checked and if any are checked. The error occurs from the of_sanitize_multicheck filter when it adds false or 1 to the $output[$key] array.

Errors:

PHP Warning:  Illegal string offset
PHP Warning:  Cannot assign an empty string to a string offset

<pre>
/**
 * Sanitization for multicheck
 *
 * @param array of checkbox values
 * @return array of sanitized values ('1' or false)
 */
function of_sanitize_multicheck( $input, $option ) {
	$output = '';
	if ( is_array( $input ) ) {
		foreach( $option['options'] as $key => $value ) {
			$output[$key] = false;
		}
		foreach( $input as $key => $value ) {
			if ( array_key_exists( $key, $option['options'] ) && $value ) {
				$output[$key] = '1';
			}
		}
	}
	return $output;
}
add_filter( 'of_sanitize_multicheck', 'of_sanitize_multicheck', 10, 2 );
</pre>

**Comment by 0xJacky** [comment]
Hi,
I just replaced `$output = ''; ` with `$output = array();`, and then fixed the issue.

**Comment by bnecreative** [comment]
@0xJacky. Yeah I found that out a while ago. I should have updated this. Thanks for confirming.
