### ISSUE TITLE
Output RGBa from color picker?

### ISSUE THREAD

**Issue by jloft** [devinsays/options-framework-theme#84]
I feel like this should be obvious or already answered somewhere, and I'm overlooking it. But how would I output the RGBa format instead of the HEX format of a color from a color picker option?

of_get_option() seems to always output the HEX value.

**Comment by apaolo228** [comment]
@devinsays ,

I know this thread is way back 2yrs ago, but I just want to ask there is an update to this plugin? Im having problem   with rgba color picker and I dont know where to start.
